= ADR-001: Convention de Nommage des Ressources Azure

- status: accepted
- deciders: [Liste des personnes impliquées dans la décision]
- date: [Date de la dernière mise à jour, format YYYY-MM-DD]

== Options Considérées
. `vm-dev-myapp-westeurope`: Abréviation du Type de Ressource + Environnement + Nom du Projet + Région.
. `vm-myapp-westeurope-dev`: Abréviation du Type de Ressource + Nom du Projet + Région + Environnement.
. `dev-westeurope-vm-myapp`: Environnement + Région + Abréviation du Type de Ressource + Nom du Projet.
. `dev-myapp-westeurope-vm`: Environnement + Nom du Projet + Région + Abréviation du Type de Ressource.
. `dev-westeurope-myapp-vm`: Environnement + Région + Nom du Projet + Abréviation du Type de Ressource.
. `myapp-dev-westeurope-vm`: Nom du Projet + Environnement + Région + Abréviation du Type de Ressource.

== Décision
La convention de nommage sélectionnée est l'option 6 (`myapp-dev-westeurope-vm`). Cette décision est prise pour assurer une clarté maximale dans l'identification des ressources Azure. De plus elle suit les recommandations de la plupart des Cloud providers.

== Conséquences (potentielles)
- La convention choisie influencera la clarté et la cohérence des noms de ressources au sein du projet.
- L'impact sur la facilité de gestion et la compréhension des ressources sera évalué.
